### PR TITLE
make graphene-stubs compatible with mypy >= 0.950

### PR DESCRIPTION
**Pull request by cpontvieux-systra**
Refs https://github.com/trialspark/graphene-stubs/issues/26

### CODE REVIEW

**Comment by anentropic** [comment]
`mypy >= 0.650` should say `mypy >= 0.950`  🙂

**Comment by karol-gruszczyk** [comment]
+1

**Comment by ben-xo** [comment]
+1

**Comment by cpontvieux-systra** [comment]
@minznerjosh or @ckarnell  can you merge this and cast a release please? It’s pretty straight forward.

**Comment by marktengi** [comment]
Thanks for submitting this @cpontvieux-systra, and sorry for the massive delay in addressing it. I incorporated this into #28, which has been merged and released.

**Pull request closed without merging**
